data=read.csv("C:/Users/miruh/Downloads/spring.csv");
print(head(data));
x=data$displacement;
y=data$force;
frame=data.frame(x,y);
model=lm(y~x-1,data=frame);
print(summary(model));
# print(plot(y~x,data=frame));
abline(model);
n=length(x);
# print(n);
beta1=1.25;
beta1hat=1.51439;
Yihat=beta1hat*data$displacement;
# print(Yihat);
Yi=data$force;
MSE=sum((Yi-Yihat)^2)/(n-1);
print(MSE);
sum_squared=sum(data$displacement^2);
print(sum_squared);
t_value=(beta1hat-beta1)/(sqrt(MSE)/sqrt(sum_squared));
print(t_value);
p_value=pt(t_value,df=n-1,lower.tail=F);
print(p_value);
